spring: 
  application: 
    name: EUREKA-HA
server: 
  port: 8761
 
# eureka:
#   instance:
#     hostname: ${EUREKA-SERVICE-NAME}
#   client:
#     register-with-eureka: false
#     fetch-registry: false
#     service-url:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#       #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:${server.port}/eureka/
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:${server.port}/eureka/