spring:
    application:
        name: ${ZIPKIN_NAME}
server:
    port: ${ZIPKIN_PORT}
eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: ${ENABLE_EUREKA}
        service-url:
            defaultZone: ${EUREKA_URL}
management:
    metrics:
        web:
            server:
                auto-time-requests: false